package com.mac.reports.report_parameter.object;

/**
 * @author Channa Mohan
 *
 * Created On Feb 17, 2015 9:52:09 AM Mohan Hibernate Mapping Generator
 */
import java.util.Date;

/**
 * MBranch generated by hbm2java
 */
public class MBranch implements java.io.Serializable {

    private String code;
    private String name;
    private Date workingDate;
    private boolean active;

    public MBranch() {
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getWorkingDate() {
        return this.workingDate;
    }

    public void setWorkingDate(Date workingDate) {
        this.workingDate = workingDate;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        return code + "-" + name;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof MBranch)) {
            return false;
        }

        MBranch castOther = (MBranch) other;

        if (this.code == null && castOther.code == null) {
            return false;
        }

        if (!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }
}
