package com.mac.reports.report_parameter.object;

/**
 * @author Channa Mohan
 *
 * Created On Feb 17, 2015 9:52:09 AM Mohan Hibernate Mapping Generator
 */
/**
 * MEmployee generated by hbm2java
 */
public class MEmployee implements java.io.Serializable {

    private String hash;
    private MBranch MBranch;
    private String code;
    private String nicNo;
    private String salutation;
    private String name;
    private String fullName;
    private String addressLine1;
    private String addressLine2;
    private String addressLine3;
    private String mobile;
    private String telephone1;
    private String telephone2;
    private String email;
    private boolean active;

    public MEmployee() {
    }

    public MEmployee(String hash, MBranch MBranch, String code, String nicNo, String salutation, String name, String fullName, String addressLine1, String addressLine2, String addressLine3, String mobile, String telephone1, String telephone2, String fax, String email, String note, boolean active) {
        this.hash = hash;
        this.MBranch = MBranch;
        this.code = code;
        this.nicNo = nicNo;
        this.salutation = salutation;
        this.name = name;
        this.fullName = fullName;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.addressLine3 = addressLine3;
        this.mobile = mobile;
        this.telephone1 = telephone1;
        this.telephone2 = telephone2;
        this.email = email;
        this.active = active;
    }

    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public MBranch getMBranch() {
        return this.MBranch;
    }

    public void setMBranch(MBranch MBranch) {
        this.MBranch = MBranch;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getNicNo() {
        return this.nicNo;
    }

    public void setNicNo(String nicNo) {
        this.nicNo = nicNo;
    }

    public String getSalutation() {
        return this.salutation;
    }

    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    public String getAddressLine3() {
        return this.addressLine3;
    }

    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTelephone1() {
        return this.telephone1;
    }

    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    public String getTelephone2() {
        return this.telephone2;
    }

    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        return code + "-" + name;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof MEmployee)) {
            return false;
        }

        MEmployee castOther = (MEmployee) other;

        if (this.code == null && castOther.code == null) {
            return false;
        }

        if (!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }
}
