package com.mac.reports.report_parameter.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Feb 17, 2015 9:52:09 AM 
  *	Mohan Hibernate Mapping Generator
  */



/**
 * MItem generated by hbm2java
 */
public class MItem  implements java.io.Serializable {


     private String hash;
     private MMainCategory MMainCategory;
     private MItemProperty MItemPropertyBySize;
     private MItemProperty MItemPropertyByUnit;
     private MItemProperty MItemPropertyByGeneric;
     private MSubCategory MSubCategory;
     private MItemProperty MItemPropertyByModel;
     private MItemProperty MItemPropertyByBrand;
     private MDepartment MDepartment;
     private MItemProperty MItemPropertyByMake;
     private String code;
     private String branch;
     private String name;
     private String barcode;
     private String sinhalaName;
     private String tamilName;
     private int quantityInPack;
     private double costPrice;
     private double wholeSaleMargin;
     private double wholeSalePrice;
     private double maxDiscountPercent;
     private double lastSalePrice;
     private double saleMargin;
     private double salePrice;
     private double averagePrice;
     private boolean batch;
     private boolean serial;
     private boolean service;
     private boolean active;

    public MItem() {
    }

	
    public MItem(String hash, String code, String branch, String name, int quantityInPack, double costPrice, double wholeSaleMargin, double wholeSalePrice, double maxDiscountPercent, double lastSalePrice, double saleMargin, double salePrice, double averagePrice, boolean batch, boolean serial, boolean service, boolean active) {
        this.hash = hash;
        this.code = code;
        this.branch = branch;
        this.name = name;
        this.quantityInPack = quantityInPack;
        this.costPrice = costPrice;
        this.wholeSaleMargin = wholeSaleMargin;
        this.wholeSalePrice = wholeSalePrice;
        this.maxDiscountPercent = maxDiscountPercent;
        this.lastSalePrice = lastSalePrice;
        this.saleMargin = saleMargin;
        this.salePrice = salePrice;
        this.averagePrice = averagePrice;
        this.batch = batch;
        this.serial = serial;
        this.service = service;
        this.active = active;
    }
    public MItem(String hash, MMainCategory MMainCategory, MItemProperty MItemPropertyBySize, MItemProperty MItemPropertyByUnit, MItemProperty MItemPropertyByGeneric, MSubCategory MSubCategory, MItemProperty MItemPropertyByModel, MItemProperty MItemPropertyByBrand, MDepartment MDepartment, MItemProperty MItemPropertyByMake, String code, String branch, String name, String barcode, String sinhalaName, String tamilName, int quantityInPack, double costPrice, double wholeSaleMargin, double wholeSalePrice, double maxDiscountPercent, double lastSalePrice, double saleMargin, double salePrice, double averagePrice, boolean batch, boolean serial, boolean service, boolean active) {
       this.hash = hash;
       this.MMainCategory = MMainCategory;
       this.MItemPropertyBySize = MItemPropertyBySize;
       this.MItemPropertyByUnit = MItemPropertyByUnit;
       this.MItemPropertyByGeneric = MItemPropertyByGeneric;
       this.MSubCategory = MSubCategory;
       this.MItemPropertyByModel = MItemPropertyByModel;
       this.MItemPropertyByBrand = MItemPropertyByBrand;
       this.MDepartment = MDepartment;
       this.MItemPropertyByMake = MItemPropertyByMake;
       this.code = code;
       this.branch = branch;
       this.name = name;
       this.barcode = barcode;
       this.sinhalaName = sinhalaName;
       this.tamilName = tamilName;
       this.quantityInPack = quantityInPack;
       this.costPrice = costPrice;
       this.wholeSaleMargin = wholeSaleMargin;
       this.wholeSalePrice = wholeSalePrice;
       this.maxDiscountPercent = maxDiscountPercent;
       this.lastSalePrice = lastSalePrice;
       this.saleMargin = saleMargin;
       this.salePrice = salePrice;
       this.averagePrice = averagePrice;
       this.batch = batch;
       this.serial = serial;
       this.service = service;
       this.active = active;
    }
   
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public MMainCategory getMMainCategory() {
        return this.MMainCategory;
    }
    
    public void setMMainCategory(MMainCategory MMainCategory) {
        this.MMainCategory = MMainCategory;
    }
    public MItemProperty getMItemPropertyBySize() {
        return this.MItemPropertyBySize;
    }
    
    public void setMItemPropertyBySize(MItemProperty MItemPropertyBySize) {
        this.MItemPropertyBySize = MItemPropertyBySize;
    }
    public MItemProperty getMItemPropertyByUnit() {
        return this.MItemPropertyByUnit;
    }
    
    public void setMItemPropertyByUnit(MItemProperty MItemPropertyByUnit) {
        this.MItemPropertyByUnit = MItemPropertyByUnit;
    }
    public MItemProperty getMItemPropertyByGeneric() {
        return this.MItemPropertyByGeneric;
    }
    
    public void setMItemPropertyByGeneric(MItemProperty MItemPropertyByGeneric) {
        this.MItemPropertyByGeneric = MItemPropertyByGeneric;
    }
    public MSubCategory getMSubCategory() {
        return this.MSubCategory;
    }
    
    public void setMSubCategory(MSubCategory MSubCategory) {
        this.MSubCategory = MSubCategory;
    }
    public MItemProperty getMItemPropertyByModel() {
        return this.MItemPropertyByModel;
    }
    
    public void setMItemPropertyByModel(MItemProperty MItemPropertyByModel) {
        this.MItemPropertyByModel = MItemPropertyByModel;
    }
    public MItemProperty getMItemPropertyByBrand() {
        return this.MItemPropertyByBrand;
    }
    
    public void setMItemPropertyByBrand(MItemProperty MItemPropertyByBrand) {
        this.MItemPropertyByBrand = MItemPropertyByBrand;
    }
    public MDepartment getMDepartment() {
        return this.MDepartment;
    }
    
    public void setMDepartment(MDepartment MDepartment) {
        this.MDepartment = MDepartment;
    }
    public MItemProperty getMItemPropertyByMake() {
        return this.MItemPropertyByMake;
    }
    
    public void setMItemPropertyByMake(MItemProperty MItemPropertyByMake) {
        this.MItemPropertyByMake = MItemPropertyByMake;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public String getSinhalaName() {
        return this.sinhalaName;
    }
    
    public void setSinhalaName(String sinhalaName) {
        this.sinhalaName = sinhalaName;
    }
    public String getTamilName() {
        return this.tamilName;
    }
    
    public void setTamilName(String tamilName) {
        this.tamilName = tamilName;
    }
    public int getQuantityInPack() {
        return this.quantityInPack;
    }
    
    public void setQuantityInPack(int quantityInPack) {
        this.quantityInPack = quantityInPack;
    }
    public double getCostPrice() {
        return this.costPrice;
    }
    
    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }
    public double getWholeSaleMargin() {
        return this.wholeSaleMargin;
    }
    
    public void setWholeSaleMargin(double wholeSaleMargin) {
        this.wholeSaleMargin = wholeSaleMargin;
    }
    public double getWholeSalePrice() {
        return this.wholeSalePrice;
    }
    
    public void setWholeSalePrice(double wholeSalePrice) {
        this.wholeSalePrice = wholeSalePrice;
    }
    public double getMaxDiscountPercent() {
        return this.maxDiscountPercent;
    }
    
    public void setMaxDiscountPercent(double maxDiscountPercent) {
        this.maxDiscountPercent = maxDiscountPercent;
    }
    public double getLastSalePrice() {
        return this.lastSalePrice;
    }
    
    public void setLastSalePrice(double lastSalePrice) {
        this.lastSalePrice = lastSalePrice;
    }
    public double getSaleMargin() {
        return this.saleMargin;
    }
    
    public void setSaleMargin(double saleMargin) {
        this.saleMargin = saleMargin;
    }
    public double getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(double salePrice) {
        this.salePrice = salePrice;
    }
    public double getAveragePrice() {
        return this.averagePrice;
    }
    
    public void setAveragePrice(double averagePrice) {
        this.averagePrice = averagePrice;
    }
    public boolean isBatch() {
        return this.batch;
    }
    
    public void setBatch(boolean batch) {
        this.batch = batch;
    }
    public boolean isSerial() {
        return this.serial;
    }
    
    public void setSerial(boolean serial) {
        this.serial = serial;
    }
    public boolean isService() {
        return this.service;
    }
    
    public void setService(boolean service) {
        this.service = service;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MItem) ){
			return false;
		}
		
		MItem castOther = ( MItem ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


