package com.mac.reports.report_parameter.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Feb 17, 2015 9:52:09 AM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * MItemProperty generated by hbm2java
 */
public class MItemProperty  implements java.io.Serializable {


     private Integer indexNo;
     private String branch;
     private String type;
     private String name;

    public MItemProperty() {
    }

	
    public MItemProperty(String branch, String type, String name) {
        this.branch = branch;
        this.type = type;
        this.name = name;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof MItemProperty) ){
			return false;
		}
		
		MItemProperty castOther = ( MItemProperty ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


