package com.mac.transaction.account_transaction.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On May 15, 2015 12:58:15 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * MReport generated by hbm2java
 */
public class MReport  implements java.io.Serializable {


     private String code;
     private String name;
     private String category;
     private byte[] report;
     private Set<RTransactionType> RTransactionTypesForSecondReport = new HashSet<RTransactionType>(0);
     private Set<RTransactionType> RTransactionTypesForFirstReport = new HashSet<RTransactionType>(0);
     private Set<RTransactionType> RTransactionTypesForThirdReport = new HashSet<RTransactionType>(0);

    public MReport() {
    }

	
    public MReport(String code, String name, String category, byte[] report) {
        this.code = code;
        this.name = name;
        this.category = category;
        this.report = report;
    }
    public MReport(String code, String name, String category, byte[] report, Set<RTransactionType> RTransactionTypesForSecondReport, Set<RTransactionType> RTransactionTypesForFirstReport, Set<RTransactionType> RTransactionTypesForThirdReport) {
       this.code = code;
       this.name = name;
       this.category = category;
       this.report = report;
       this.RTransactionTypesForSecondReport = RTransactionTypesForSecondReport;
       this.RTransactionTypesForFirstReport = RTransactionTypesForFirstReport;
       this.RTransactionTypesForThirdReport = RTransactionTypesForThirdReport;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public byte[] getReport() {
        return this.report;
    }
    
    public void setReport(byte[] report) {
        this.report = report;
    }
    public Set<RTransactionType> getRTransactionTypesForSecondReport() {
        return this.RTransactionTypesForSecondReport;
    }
    
    public void setRTransactionTypesForSecondReport(Set<RTransactionType> RTransactionTypesForSecondReport) {
        this.RTransactionTypesForSecondReport = RTransactionTypesForSecondReport;
    }
    public Set<RTransactionType> getRTransactionTypesForFirstReport() {
        return this.RTransactionTypesForFirstReport;
    }
    
    public void setRTransactionTypesForFirstReport(Set<RTransactionType> RTransactionTypesForFirstReport) {
        this.RTransactionTypesForFirstReport = RTransactionTypesForFirstReport;
    }
    public Set<RTransactionType> getRTransactionTypesForThirdReport() {
        return this.RTransactionTypesForThirdReport;
    }
    
    public void setRTransactionTypesForThirdReport(Set<RTransactionType> RTransactionTypesForThirdReport) {
        this.RTransactionTypesForThirdReport = RTransactionTypesForThirdReport;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MReport) ){
			return false;
		}
		
		MReport castOther = ( MReport ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


