package com.mac.transaction.account_transaction.object;

/**
 * @author Channa Mohan
 *
 * Created On May 15, 2015 12:58:15 PM Mohan Hibernate Mapping Generator
 */
import java.util.HashSet;
import java.util.Set;

/**
 * RTransactionType generated by hbm2java
 */
public class RTransactionType implements java.io.Serializable {

    private String code;
    private MReport MReportByThirdReport;
    private MReport MReportByFirstReport;
    private MReport MReportBySecondReport;
    private RTransactionType RTransactionType;
    private String name;
    private String formType;
    private String type;
    private boolean itemIn;
    private boolean itemOut;
    private String inStore;
    private String outStore;
    private boolean fixedPrice;
    private String priceType;
    private boolean percentageDiscount;
    private boolean settlementTransaction;
    private boolean expireDate;
    private boolean client;
    private boolean supplier;
    private boolean printFirstReport;
    private boolean printSecondReport;
    private boolean printThirdReport;
    private boolean creditAmount;
    private boolean debitAmount;
    private boolean payment;
    private boolean active;
    private Set<TTransactionSummary> TTransactionSummaries = new HashSet<TTransactionSummary>(0);
    private Set<RTransactionType> RTransactionTypes = new HashSet<RTransactionType>(0);

    public RTransactionType() {
    }

    public RTransactionType(String code, String name, String formType, String type, boolean itemIn, boolean itemOut, boolean fixedPrice, String priceType, boolean percentageDiscount, boolean settlementTransaction, boolean expireDate, boolean client, boolean supplier, boolean printFirstReport, boolean printSecondReport, boolean printThirdReport, boolean creditAmount, boolean debitAmount, boolean active) {
        this.code = code;
        this.name = name;
        this.formType = formType;
        this.type = type;
        this.itemIn = itemIn;
        this.itemOut = itemOut;
        this.fixedPrice = fixedPrice;
        this.priceType = priceType;
        this.percentageDiscount = percentageDiscount;
        this.settlementTransaction = settlementTransaction;
        this.expireDate = expireDate;
        this.client = client;
        this.supplier = supplier;
        this.printFirstReport = printFirstReport;
        this.printSecondReport = printSecondReport;
        this.printThirdReport = printThirdReport;
        this.creditAmount = creditAmount;
        this.debitAmount = debitAmount;
        this.active = active;
    }

    public RTransactionType(String code, MReport MReportByThirdReport, MReport MReportByFirstReport, MReport MReportBySecondReport, RTransactionType RTransactionType, String name, String formType, String type, boolean itemIn, boolean itemOut, String inStore, String outStore, boolean fixedPrice, String priceType, boolean percentageDiscount, boolean settlementTransaction, boolean expireDate, boolean client, boolean supplier, boolean printFirstReport, boolean printSecondReport, boolean printThirdReport, boolean creditAmount, boolean debitAmount, boolean active, Set<TTransactionSummary> TTransactionSummaries, Set<RTransactionType> RTransactionTypes) {
        this.code = code;
        this.MReportByThirdReport = MReportByThirdReport;
        this.MReportByFirstReport = MReportByFirstReport;
        this.MReportBySecondReport = MReportBySecondReport;
        this.RTransactionType = RTransactionType;
        this.name = name;
        this.formType = formType;
        this.type = type;
        this.itemIn = itemIn;
        this.itemOut = itemOut;
        this.inStore = inStore;
        this.outStore = outStore;
        this.fixedPrice = fixedPrice;
        this.priceType = priceType;
        this.percentageDiscount = percentageDiscount;
        this.settlementTransaction = settlementTransaction;
        this.expireDate = expireDate;
        this.client = client;
        this.supplier = supplier;
        this.printFirstReport = printFirstReport;
        this.printSecondReport = printSecondReport;
        this.printThirdReport = printThirdReport;
        this.creditAmount = creditAmount;
        this.debitAmount = debitAmount;
        this.active = active;
        this.TTransactionSummaries = TTransactionSummaries;
        this.RTransactionTypes = RTransactionTypes;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public MReport getMReportByThirdReport() {
        return this.MReportByThirdReport;
    }

    public void setMReportByThirdReport(MReport MReportByThirdReport) {
        this.MReportByThirdReport = MReportByThirdReport;
    }

    public MReport getMReportByFirstReport() {
        return this.MReportByFirstReport;
    }

    public void setMReportByFirstReport(MReport MReportByFirstReport) {
        this.MReportByFirstReport = MReportByFirstReport;
    }

    public MReport getMReportBySecondReport() {
        return this.MReportBySecondReport;
    }

    public void setMReportBySecondReport(MReport MReportBySecondReport) {
        this.MReportBySecondReport = MReportBySecondReport;
    }

    public RTransactionType getRTransactionType() {
        return this.RTransactionType;
    }

    public void setRTransactionType(RTransactionType RTransactionType) {
        this.RTransactionType = RTransactionType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFormType() {
        return this.formType;
    }

    public void setFormType(String formType) {
        this.formType = formType;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isItemIn() {
        return this.itemIn;
    }

    public void setItemIn(boolean itemIn) {
        this.itemIn = itemIn;
    }

    public boolean isItemOut() {
        return this.itemOut;
    }

    public void setItemOut(boolean itemOut) {
        this.itemOut = itemOut;
    }

    public String getInStore() {
        return this.inStore;
    }

    public void setInStore(String inStore) {
        this.inStore = inStore;
    }

    public String getOutStore() {
        return this.outStore;
    }

    public void setOutStore(String outStore) {
        this.outStore = outStore;
    }

    public boolean isFixedPrice() {
        return this.fixedPrice;
    }

    public void setFixedPrice(boolean fixedPrice) {
        this.fixedPrice = fixedPrice;
    }

    public String getPriceType() {
        return this.priceType;
    }

    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    public boolean isPercentageDiscount() {
        return this.percentageDiscount;
    }

    public void setPercentageDiscount(boolean percentageDiscount) {
        this.percentageDiscount = percentageDiscount;
    }

    public boolean isSettlementTransaction() {
        return this.settlementTransaction;
    }

    public void setSettlementTransaction(boolean settlementTransaction) {
        this.settlementTransaction = settlementTransaction;
    }

    public boolean isExpireDate() {
        return this.expireDate;
    }

    public void setExpireDate(boolean expireDate) {
        this.expireDate = expireDate;
    }

    public boolean isClient() {
        return this.client;
    }

    public void setClient(boolean client) {
        this.client = client;
    }

    public boolean isSupplier() {
        return this.supplier;
    }

    public void setSupplier(boolean supplier) {
        this.supplier = supplier;
    }

    public boolean isPrintFirstReport() {
        return this.printFirstReport;
    }

    public void setPrintFirstReport(boolean printFirstReport) {
        this.printFirstReport = printFirstReport;
    }

    public boolean isPrintSecondReport() {
        return this.printSecondReport;
    }

    public void setPrintSecondReport(boolean printSecondReport) {
        this.printSecondReport = printSecondReport;
    }

    public boolean isPrintThirdReport() {
        return this.printThirdReport;
    }

    public void setPrintThirdReport(boolean printThirdReport) {
        this.printThirdReport = printThirdReport;
    }

    public boolean isCreditAmount() {
        return this.creditAmount;
    }

    public void setCreditAmount(boolean creditAmount) {
        this.creditAmount = creditAmount;
    }

    public boolean isDebitAmount() {
        return this.debitAmount;
    }

    public void setDebitAmount(boolean debitAmount) {
        this.debitAmount = debitAmount;
    }

    public boolean isPayment() {
        return payment;
    }

    public void setPayment(boolean payment) {
        this.payment = payment;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Set<TTransactionSummary> getTTransactionSummaries() {
        return this.TTransactionSummaries;
    }

    public void setTTransactionSummaries(Set<TTransactionSummary> TTransactionSummaries) {
        this.TTransactionSummaries = TTransactionSummaries;
    }

    public Set<RTransactionType> getRTransactionTypes() {
        return this.RTransactionTypes;
    }

    public void setRTransactionTypes(Set<RTransactionType> RTransactionTypes) {
        this.RTransactionTypes = RTransactionTypes;
    }

    @Override
    public String toString() {
        return code + "-" + name;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof RTransactionType)) {
            return false;
        }

        RTransactionType castOther = (RTransactionType) other;

        if (this.code == null && castOther.code == null) {
            return false;
        }

        if (!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }
}
