package com.mac.registration.sub_category.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Feb 11, 2015 11:34:23 AM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * MMainCategory generated by hbm2java
 */
public class MMainCategory  implements java.io.Serializable {


     private String hash;
     private MDepartment MDepartment;
     private String code;
     private String branch;
     private String name;
     private boolean active;
     private Set<MSubCategory> MSubCategories = new HashSet<MSubCategory>(0);

    public MMainCategory() {
    }

	
    public MMainCategory(String hash, MDepartment MDepartment, String code, String branch, String name, boolean active) {
        this.hash = hash;
        this.MDepartment = MDepartment;
        this.code = code;
        this.branch = branch;
        this.name = name;
        this.active = active;
    }
    public MMainCategory(String hash, MDepartment MDepartment, String code, String branch, String name, boolean active, Set<MSubCategory> MSubCategories) {
       this.hash = hash;
       this.MDepartment = MDepartment;
       this.code = code;
       this.branch = branch;
       this.name = name;
       this.active = active;
       this.MSubCategories = MSubCategories;
    }
   
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public MDepartment getMDepartment() {
        return this.MDepartment;
    }
    
    public void setMDepartment(MDepartment MDepartment) {
        this.MDepartment = MDepartment;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set<MSubCategory> getMSubCategories() {
        return this.MSubCategories;
    }
    
    public void setMSubCategories(Set<MSubCategory> MSubCategories) {
        this.MSubCategories = MSubCategories;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MMainCategory) ){
			return false;
		}
		
		MMainCategory castOther = ( MMainCategory ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


