package com.mac.transaction.item_transaction_new.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Mar 20, 2015 9:41:46 AM 
  *	Mohan Hibernate Mapping Generator
  */



/**
 * TItemMovement generated by hbm2java
 */
public class TItemMovement  implements java.io.Serializable {


     private Integer indexNo;
     private MStore MStore;
     private MItem MItem;
     private TTransactionSummary TTransactionSummary;
     private String branch;
     private Integer inQuantity;
     private Integer outQuantity;
     private Double avaragePrice;
     private String status;

    public TItemMovement() {
    }

    public TItemMovement(MStore MStore, MItem MItem, TTransactionSummary TTransactionSummary, String branch, Integer inQuantity, Integer outQuantity, Double avaragePrice, String status) {
       this.MStore = MStore;
       this.MItem = MItem;
       this.TTransactionSummary = TTransactionSummary;
       this.branch = branch;
       this.inQuantity = inQuantity;
       this.outQuantity = outQuantity;
       this.avaragePrice = avaragePrice;
       this.status = status;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public MStore getMStore() {
        return this.MStore;
    }
    
    public void setMStore(MStore MStore) {
        this.MStore = MStore;
    }
    public MItem getMItem() {
        return this.MItem;
    }
    
    public void setMItem(MItem MItem) {
        this.MItem = MItem;
    }
    public TTransactionSummary getTTransactionSummary() {
        return this.TTransactionSummary;
    }
    
    public void setTTransactionSummary(TTransactionSummary TTransactionSummary) {
        this.TTransactionSummary = TTransactionSummary;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public Integer getInQuantity() {
        return this.inQuantity;
    }
    
    public void setInQuantity(Integer inQuantity) {
        this.inQuantity = inQuantity;
    }
    public Integer getOutQuantity() {
        return this.outQuantity;
    }
    
    public void setOutQuantity(Integer outQuantity) {
        this.outQuantity = outQuantity;
    }
    public Double getAvaragePrice() {
        return this.avaragePrice;
    }
    
    public void setAvaragePrice(Double avaragePrice) {
        this.avaragePrice = avaragePrice;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }





	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof TItemMovement) ){
			return false;
		}
		
		TItemMovement castOther = ( TItemMovement ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


