package com.mac.transaction.item_transaction_new.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Mar 20, 2015 9:41:46 AM 
  *	Mohan Hibernate Mapping Generator
  */



/**
 * TSerialMovement generated by hbm2java
 */
public class TSerialMovement  implements java.io.Serializable {


     private Integer indexNo;
     private TTransactionDetail TTransactionDetail;
     private MStore MStoreByOutStore;
     private MStore MStoreByInStore;
     private MItem MItem;
     private String branch;
     private String serialNumber;
     private String status;

    public TSerialMovement() {
    }

	
    public TSerialMovement(TTransactionDetail TTransactionDetail, MItem MItem, String branch, String serialNumber) {
        this.TTransactionDetail = TTransactionDetail;
        this.MItem = MItem;
        this.branch = branch;
        this.serialNumber = serialNumber;
    }
    public TSerialMovement(TTransactionDetail TTransactionDetail, MStore MStoreByOutStore, MStore MStoreByInStore, MItem MItem, String branch, String serialNumber, String status) {
       this.TTransactionDetail = TTransactionDetail;
       this.MStoreByOutStore = MStoreByOutStore;
       this.MStoreByInStore = MStoreByInStore;
       this.MItem = MItem;
       this.branch = branch;
       this.serialNumber = serialNumber;
       this.status = status;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public TTransactionDetail getTTransactionDetail() {
        return this.TTransactionDetail;
    }
    
    public void setTTransactionDetail(TTransactionDetail TTransactionDetail) {
        this.TTransactionDetail = TTransactionDetail;
    }
    public MStore getMStoreByOutStore() {
        return this.MStoreByOutStore;
    }
    
    public void setMStoreByOutStore(MStore MStoreByOutStore) {
        this.MStoreByOutStore = MStoreByOutStore;
    }
    public MStore getMStoreByInStore() {
        return this.MStoreByInStore;
    }
    
    public void setMStoreByInStore(MStore MStoreByInStore) {
        this.MStoreByInStore = MStoreByInStore;
    }
    public MItem getMItem() {
        return this.MItem;
    }
    
    public void setMItem(MItem MItem) {
        this.MItem = MItem;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }





	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof TSerialMovement) ){
			return false;
		}
		
		TSerialMovement castOther = ( TSerialMovement ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


