package com.mac.transaction.item_transaction_new.object;

import com.mac.transaction.account_transaction.object.*;

/**
 * @author Channa Mohan
 *
 * Created On May 15, 2015 12:58:15 PM Mohan Hibernate Mapping Generator
 */
/**
 * TTransactionSettlement generated by hbm2java
 */
public class TTransactionSettlement implements java.io.Serializable {

    private Integer indexNo;
    private int transactionSummary;
    private int settleTransactionSummary;
    private String branch;
    private double amount;
    private String status;

    public TTransactionSettlement() {
    }

    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    public int getTransactionSummary() {
        return transactionSummary;
    }

    public void setTransactionSummary(int transactionSummary) {
        this.transactionSummary = transactionSummary;
    }

    public int getSettleTransactionSummary() {
        return settleTransactionSummary;
    }

    public void setSettleTransactionSummary(int settleTransactionSummary) {
        this.settleTransactionSummary = settleTransactionSummary;
    }

    public String getBranch() {
        return this.branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public double getAmount() {
        return this.amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }

        if (other == null) {
            return false;
        }

        if (!(other instanceof TTransactionSettlement)) {
            return false;
        }

        TTransactionSettlement castOther = (TTransactionSettlement) other;

        if (this.indexNo == null && castOther.indexNo == null) {
            return false;
        }

        if (!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }
}
