package com.mac.registration.account.object;
// Generated Jan 3, 2015 12:03:56 PM by Hibernate Tools 3.2.1.GA



/**
 * MAccount generated by hbm2java
 */
public class MAccount  implements java.io.Serializable {


     private String code;
     private MAccountCategory MAccountCategory;
     private String name;
     private String accountGroup;
     private Integer printOrder;
     private String beforeWord;
     private String afterWord;
     private Boolean active;

    public MAccount() {
    }

	
    public MAccount(String code) {
        this.code = code;
    }
    public MAccount(String code, MAccountCategory MAccountCategory, String name, String accountGroup, Integer printOrder, String beforeWord, String afterWord, Boolean active) {
       this.code = code;
       this.MAccountCategory = MAccountCategory;
       this.name = name;
       this.accountGroup = accountGroup;
       this.printOrder = printOrder;
       this.beforeWord = beforeWord;
       this.afterWord = afterWord;
       this.active = active;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public MAccountCategory getMAccountCategory() {
        return this.MAccountCategory;
    }
    
    public void setMAccountCategory(MAccountCategory MAccountCategory) {
        this.MAccountCategory = MAccountCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAccountGroup() {
        return this.accountGroup;
    }
    
    public void setAccountGroup(String accountGroup) {
        this.accountGroup = accountGroup;
    }
    public Integer getPrintOrder() {
        return this.printOrder;
    }
    
    public void setPrintOrder(Integer printOrder) {
        this.printOrder = printOrder;
    }
    public String getBeforeWord() {
        return this.beforeWord;
    }
    
    public void setBeforeWord(String beforeWord) {
        this.beforeWord = beforeWord;
    }
    public String getAfterWord() {
        return this.afterWord;
    }
    
    public void setAfterWord(String afterWord) {
        this.afterWord = afterWord;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


