package com.mac.zsystem.transaction.transaction.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Oct 15, 2014 2:34:02 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.Date;

/**
 * TransactionHistory generated by hbm2java
 */
public class TransactionHistory  implements java.io.Serializable {


     private Integer indexNo;
     private Transaction transaction;
     private String action;
     private String employee;
     private String note;
     private Date dateTime;

    public TransactionHistory() {
    }

	
    public TransactionHistory(Transaction transaction, String action, String employee, Date dateTime) {
        this.transaction = transaction;
        this.action = action;
        this.employee = employee;
        this.dateTime = dateTime;
    }
    public TransactionHistory(Transaction transaction, String action, String employee, String note, Date dateTime) {
       this.transaction = transaction;
       this.action = action;
       this.employee = employee;
       this.note = note;
       this.dateTime = dateTime;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(String employee) {
        this.employee = employee;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }





	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof TransactionHistory) ){
			return false;
		}
		
		TransactionHistory castOther = ( TransactionHistory ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


