package com.mac.zsystem.transaction.transaction.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Oct 15, 2014 2:34:02 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer indexNo;
     private TransactionType transactionType;
     private Date transactionDate;
     private String referenceNo;
     private String documentNo;
     private Integer loan;
     private Integer cashierSession;
     private String branch;
     private String client;
     private String note;
     private String status;
     private Set<TransactionHistory> transactionHistories = new HashSet<TransactionHistory>(0);

    public Transaction() {
    }

	
    public Transaction(TransactionType transactionType, Date transactionDate, String referenceNo, String branch, String status) {
        this.transactionType = transactionType;
        this.transactionDate = transactionDate;
        this.referenceNo = referenceNo;
        this.branch = branch;
        this.status = status;
    }
    public Transaction(TransactionType transactionType, Date transactionDate, String referenceNo, String documentNo, Integer loan, Integer cashierSession, String branch, String client, String note, String status, Set<TransactionHistory> transactionHistories) {
       this.transactionType = transactionType;
       this.transactionDate = transactionDate;
       this.referenceNo = referenceNo;
       this.documentNo = documentNo;
       this.loan = loan;
       this.cashierSession = cashierSession;
       this.branch = branch;
       this.client = client;
       this.note = note;
       this.status = status;
       this.transactionHistories = transactionHistories;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getReferenceNo() {
        return this.referenceNo;
    }
    
    public void setReferenceNo(String referenceNo) {
        this.referenceNo = referenceNo;
    }
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public Integer getLoan() {
        return this.loan;
    }
    
    public void setLoan(Integer loan) {
        this.loan = loan;
    }
    public Integer getCashierSession() {
        return this.cashierSession;
    }
    
    public void setCashierSession(Integer cashierSession) {
        this.cashierSession = cashierSession;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<TransactionHistory> getTransactionHistories() {
        return this.transactionHistories;
    }
    
    public void setTransactionHistories(Set<TransactionHistory> transactionHistories) {
        this.transactionHistories = transactionHistories;
    }





	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof Transaction) ){
			return false;
		}
		
		Transaction castOther = ( Transaction ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


