package com.mac.zsystem.transaction.transaction.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Oct 15, 2014 2:34:02 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private String code;
     private String name;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public TransactionType() {
    }

	
    public TransactionType(String code) {
        this.code = code;
    }
    public TransactionType(String code, String name, Set<Transaction> transactions) {
       this.code = code;
       this.name = name;
       this.transactions = transactions;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof TransactionType) ){
			return false;
		}
		
		TransactionType castOther = ( TransactionType ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


