/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mac.account.ztemplate.account_entry;

import com.mac.account.ztemplate.account_entry.object.Entry;
import com.mac.af.component.base.button.action.Action;
import com.mac.af.component.base.button.action.ActionUtil;
import com.mac.af.panel.object.CInputComponentBinder;
import com.mac.af.panel.object.DefaultObjectCreator;
import com.mac.account.ztemplate.account_entry.object.AccountEntryTransaction;
import com.mac.af.core.message.mOptionPane;
import com.mac.af.panel.object.ObjectCreatorException;
import com.mac.af.resources.ApplicationResources;
import com.mac.registration.account.object.MAccount;
import com.mac.zsystem.util.ReferenceGenerator;
import com.mac.zsystem.transaction.account.account_setting.AccountSettingCreditOrDebit;
import com.mac.zsystem.util.ReferenceGenerator;
import java.awt.Component;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author SMTK
 */
public abstract class PCAccountEntry extends DefaultObjectCreator<AccountEntryTransaction> {

    /**
     * Creates new form PCCheque
     */
    public PCAccountEntry() {
        initComponents();
        initOthers();
    }

    protected abstract String ReferenceGeneratorPrefix();

    protected abstract String getTransactionTypeCode();

    protected abstract String getEntryType();

    protected abstract void addJournelEntry(Entry journalEntry);

    public abstract List getAccounts();

    public abstract Double getTotalCredit();

    public abstract Double getTotalDebit();

    @Action
    public void doAdd() {
        if (txtDebitAmount.getCValue() > 0.0 || txtCreditAmount.getCValue() > 0.0) {
            if (txtDebitAmount.getCValue() > 0.0 && txtCreditAmount.getCValue() > 0.0) {
                mOptionPane.showMessageDialog(this, "Invalide Transaction", "Error", mOptionPane.WARNING_MESSAGE);
            } else {

                Entry entry = new Entry();
                entry.setAccount((MAccount) cboAccount.getCValue());
                entry.setDescription(txtDescription.getCValue());
                entry.setCreditAmount(txtCreditAmount.getCValue());
                entry.setDebitAmount(txtDebitAmount.getCValue());

                if (txtCreditAmount.getCValue() > 0) {
                    entry.setCreditOrDebit(AccountSettingCreditOrDebit.CREDIT);
                }
                if (txtDebitAmount.getCValue() > 0) {
                    entry.setCreditOrDebit(AccountSettingCreditOrDebit.DEBIT);
                }
                addJournelEntry(entry);

                Double totalCredit = getTotalCredit();
                Double totalDebit = getTotalDebit();

                txtTotalCreditAmount.setCValue(totalCredit);
                txtTotalDebitAmount.setCValue(totalDebit);

                try {
                    getValueAbstract().setTotalCreditAmount(totalCredit);
                    getValueAbstract().setTotalDebitAmount(totalDebit);
                } catch (ObjectCreatorException ex) {
                }
                resetJournel();
            }
        } else {
            mOptionPane.showMessageDialog(this, "Invalide Transaction", "Error", mOptionPane.WARNING_MESSAGE);
        }
    }

    @Action
    public void reset() {
        resetAll();
    }

    private void resetJournel() {
        cboAccount.resetValue();
        txtDescription.resetValue();
        txtCreditAmount.resetValue();
        txtDebitAmount.resetValue();
    }

    private void resetAll() {
        resetJournel();
        txtDocumentNo.resetValue();
        txtNote.resetValue();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initOthers() {
        ActionUtil actionUtil = new ActionUtil(this);
        actionUtil.setAction(btnAdd, "doAdd");
        actionUtil.setAction(btnReset, "reset");

        //ICONS
        btnAdd.setIcon(ApplicationResources.getImageIcon(ApplicationResources.ACTION_ADD, 16, 16));
        btnReset.setIcon(ApplicationResources.getImageIcon(ApplicationResources.ACTION_RESET, 16, 16));

        txtReferenceNo.setGenerator(ReferenceGenerator.getInstance(ReferenceGeneratorPrefix()));

        resetFields();
    }

    private void resetEntryTypes() {
//        switch (getEntryType()) {
//            case AccountEntry.ACCOUNT_ENTRY_CREDIT_ONLY:
//                //CREDIT
//                hideComponent(txtCreditAmount, true);
//                hideComponent(lblCreditAmount, true);
//
//                hideComponent(txtTotalCreditAmount, true);
//                hideComponent(lblTotalCreditAmount, true);
//
//                //DEBIT
//                hideComponent(txtDebitAmount, false);
//                hideComponent(lblDebitAmount, false);
//
//                hideComponent(txtTotalDebitAmount, false);
//                hideComponent(lblTotalDebitAmount, false);
//
//                break;
//            case AccountEntry.ACCOUNT_ENTRY_DEBIT_ONLY:
//                //CREDIT
//                hideComponent(txtCreditAmount, false);
//                hideComponent(lblCreditAmount, false);
//
//                hideComponent(txtTotalCreditAmount, false);
//                hideComponent(lblTotalCreditAmount, false);
//
//                //DEBIT
//                hideComponent(txtDebitAmount, true);
//                hideComponent(lblDebitAmount, true);
//
//                hideComponent(txtTotalDebitAmount, true);
//                hideComponent(lblTotalDebitAmount, true);
//                break;
//            case AccountEntry.ACCOUNT_ENTRY_CREDIT_OR_DEBIT:
//                //CREDIT
//                hideComponent(txtCreditAmount, true);
//                hideComponent(lblCreditAmount, true);
//
//                hideComponent(txtTotalCreditAmount, true);
//                hideComponent(lblTotalCreditAmount, true);
//
//                //DEBIT
//                hideComponent(txtDebitAmount, true);
//                hideComponent(lblDebitAmount, true);
//
//                hideComponent(txtTotalDebitAmount, true);
//                hideComponent(lblTotalDebitAmount, true);
//                break;
//            default:
//                throw new AssertionError();
//        }
    }

    private void hideComponent(Component c, boolean state) {
        c.setVisible(state);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cDLabel1 = new com.mac.af.component.derived.display.label.CDLabel();
        cDLabel2 = new com.mac.af.component.derived.display.label.CDLabel();
        cDLabel3 = new com.mac.af.component.derived.display.label.CDLabel();
        cDLabel4 = new com.mac.af.component.derived.display.label.CDLabel();
        txtReferenceNo = new com.mac.af.component.derived.input.textfield.CIStringField();
        txtDocumentNo = new com.mac.af.component.derived.input.textfield.CIStringField();
        txtTransactionDate = new com.mac.af.component.derived.input.textfield.CIDateField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new com.mac.af.component.derived.input.textarea.CITextArea();
        cDLabel5 = new com.mac.af.component.derived.display.label.CDLabel();
        cboAccount = new com.mac.af.component.derived.input.combobox.CIComboBox()
        {
            @Override
            public List getComboData(){
                return getAccounts();
            }
        }
        ;
        lblCreditAmount = new com.mac.af.component.derived.display.label.CDLabel();
        txtCreditAmount = new com.mac.af.component.derived.input.textfield.CIDoubleField();
        txtDebitAmount = new com.mac.af.component.derived.input.textfield.CIDoubleField();
        lblDebitAmount = new com.mac.af.component.derived.display.label.CDLabel();
        lblTotalCreditAmount = new com.mac.af.component.derived.display.label.CDLabel();
        lblTotalDebitAmount = new com.mac.af.component.derived.display.label.CDLabel();
        txtTotalCreditAmount = new com.mac.af.component.derived.display.textfield.CDDoubleField();
        txtTotalDebitAmount = new com.mac.af.component.derived.display.textfield.CDDoubleField();
        cDLabel10 = new com.mac.af.component.derived.display.label.CDLabel();
        txtDescription = new com.mac.af.component.derived.input.textfield.CIStringField();
        btnReset = new com.mac.af.component.derived.command.button.CCButton();
        btnAdd = new com.mac.af.component.derived.command.button.CCButton();

        cDLabel1.setText("Reference No :");

        cDLabel2.setText("Document No :");

        cDLabel3.setText("Transaction Date :");

        cDLabel4.setText("Note :");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        cDLabel5.setText("Account :");

        lblCreditAmount.setText("Credit Amount :");

        lblDebitAmount.setText("Debit Amount :");

        lblTotalCreditAmount.setText("Total Credit Amount :");

        lblTotalDebitAmount.setText("Total Debit Amount :");

        cDLabel10.setText("Description :");

        btnReset.setText("Reset");

        btnAdd.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cDLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtTransactionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDocumentNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReferenceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCreditAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDebitAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalCreditAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalDebitAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReferenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cDLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cDLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mac.af.component.derived.command.button.CCButton btnAdd;
    private com.mac.af.component.derived.command.button.CCButton btnReset;
    private com.mac.af.component.derived.display.label.CDLabel cDLabel1;
    private com.mac.af.component.derived.display.label.CDLabel cDLabel10;
    private com.mac.af.component.derived.display.label.CDLabel cDLabel2;
    private com.mac.af.component.derived.display.label.CDLabel cDLabel3;
    private com.mac.af.component.derived.display.label.CDLabel cDLabel4;
    private com.mac.af.component.derived.display.label.CDLabel cDLabel5;
    private com.mac.af.component.derived.input.combobox.CIComboBox cboAccount;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mac.af.component.derived.display.label.CDLabel lblCreditAmount;
    private com.mac.af.component.derived.display.label.CDLabel lblDebitAmount;
    private com.mac.af.component.derived.display.label.CDLabel lblTotalCreditAmount;
    private com.mac.af.component.derived.display.label.CDLabel lblTotalDebitAmount;
    private com.mac.af.component.derived.input.textfield.CIDoubleField txtCreditAmount;
    private com.mac.af.component.derived.input.textfield.CIDoubleField txtDebitAmount;
    private com.mac.af.component.derived.input.textfield.CIStringField txtDescription;
    private com.mac.af.component.derived.input.textfield.CIStringField txtDocumentNo;
    private com.mac.af.component.derived.input.textarea.CITextArea txtNote;
    private com.mac.af.component.derived.input.textfield.CIStringField txtReferenceNo;
    private com.mac.af.component.derived.display.textfield.CDDoubleField txtTotalCreditAmount;
    private com.mac.af.component.derived.display.textfield.CDDoubleField txtTotalDebitAmount;
    private com.mac.af.component.derived.input.textfield.CIDateField txtTransactionDate;
    // End of variables declaration//GEN-END:variables

    @Override
    protected List<Component> getIdentityComponents() {
        return Arrays.asList(
                (Component) txtReferenceNo);
    }

    @Override
    protected List<Component> getEssentialComponents() {
        return Arrays.asList();
    }

    @Override
    protected List<Component> getOtherFieldComponents() {
        return Arrays.asList(
                (Component) txtDocumentNo,
                (Component) txtTransactionDate,
                (Component) txtNote,
                (Component) cboAccount,
                (Component) txtDescription,
                (Component) txtCreditAmount,
                (Component) txtDebitAmount);
    }

    @Override
    protected List<CInputComponentBinder> getInputComponentBinders() {
        return Arrays.asList(
                new CInputComponentBinder(txtReferenceNo, new String[]{"referenceNo"}),
                new CInputComponentBinder(txtDocumentNo, new String[]{"documentNo"}),
                new CInputComponentBinder(txtTransactionDate, new String[]{"transactionDate"}),
                new CInputComponentBinder(txtNote, new String[]{"note"}));
    }

    @Override
    protected List<Component> getUneditableComponents() {
        return Arrays.asList(
                (Component) txtReferenceNo,
                (Component) txtTransactionDate);
    }

    @Override
    public void resetFields() {
        super.resetFields();
        resetEntryTypes();
    }

    @Override
    protected Class<? extends AccountEntryTransaction> getObjectClass() {
        return AccountEntryTransaction.class;
    }
}
