package com.mac.registration.item.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Feb 27, 2015 12:48:50 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * MSubCategory generated by hbm2java
 */
public class MSubCategory  implements java.io.Serializable {


     private String hash;
     private MMainCategory MMainCategory;
     private String code;
     private String branch;
     private String name;
     private boolean active;
     private Set<MItem> MItems = new HashSet<MItem>(0);

    public MSubCategory() {
    }

	
    public MSubCategory(String hash, MMainCategory MMainCategory, String code, String branch, String name, boolean active) {
        this.hash = hash;
        this.MMainCategory = MMainCategory;
        this.code = code;
        this.branch = branch;
        this.name = name;
        this.active = active;
    }
    public MSubCategory(String hash, MMainCategory MMainCategory, String code, String branch, String name, boolean active, Set<MItem> MItems) {
       this.hash = hash;
       this.MMainCategory = MMainCategory;
       this.code = code;
       this.branch = branch;
       this.name = name;
       this.active = active;
       this.MItems = MItems;
    }
   
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public MMainCategory getMMainCategory() {
        return this.MMainCategory;
    }
    
    public void setMMainCategory(MMainCategory MMainCategory) {
        this.MMainCategory = MMainCategory;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set<MItem> getMItems() {
        return this.MItems;
    }
    
    public void setMItems(Set<MItem> MItems) {
        this.MItems = MItems;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MSubCategory) ){
			return false;
		}
		
		MSubCategory castOther = ( MSubCategory ) other; 

		if(this.hash==null && castOther.hash==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.hash, castOther.hash)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


