package com.mac.zsystem.permission.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Jul 2, 2015 3:46:30 PM 
  *	Mohan Hibernate Mapping Generator
  */



/**
 * MEmployee generated by hbm2java
 */
public class MEmployee  implements java.io.Serializable {


     private String hash;
     private RUserRole RUserRole;
     private String code;
     private String branch;
     private String nicNo;
     private String salutation;
     private String name;
     private String fullName;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private String mobile;
     private String telephone1;
     private String telephone2;
     private String fax;
     private String email;
     private String note;
     private String userName;
     private String password;
     private Integer photo;
     private boolean active;

    public MEmployee() {
    }

	
    public MEmployee(String hash, String code, String branch, String nicNo, String salutation, String name, String fullName, String addressLine1, String addressLine2, String addressLine3, String mobile, String telephone1, String telephone2, String fax, String email, String note, boolean active) {
        this.hash = hash;
        this.code = code;
        this.branch = branch;
        this.nicNo = nicNo;
        this.salutation = salutation;
        this.name = name;
        this.fullName = fullName;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.addressLine3 = addressLine3;
        this.mobile = mobile;
        this.telephone1 = telephone1;
        this.telephone2 = telephone2;
        this.fax = fax;
        this.email = email;
        this.note = note;
        this.active = active;
    }
    public MEmployee(String hash, RUserRole RUserRole, String code, String branch, String nicNo, String salutation, String name, String fullName, String addressLine1, String addressLine2, String addressLine3, String mobile, String telephone1, String telephone2, String fax, String email, String note, String userName, String password, Integer photo, boolean active) {
       this.hash = hash;
       this.RUserRole = RUserRole;
       this.code = code;
       this.branch = branch;
       this.nicNo = nicNo;
       this.salutation = salutation;
       this.name = name;
       this.fullName = fullName;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.mobile = mobile;
       this.telephone1 = telephone1;
       this.telephone2 = telephone2;
       this.fax = fax;
       this.email = email;
       this.note = note;
       this.userName = userName;
       this.password = password;
       this.photo = photo;
       this.active = active;
    }
   
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public RUserRole getRUserRole() {
        return this.RUserRole;
    }
    
    public void setRUserRole(RUserRole RUserRole) {
        this.RUserRole = RUserRole;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getNicNo() {
        return this.nicNo;
    }
    
    public void setNicNo(String nicNo) {
        this.nicNo = nicNo;
    }
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getTelephone1() {
        return this.telephone1;
    }
    
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }
    public String getTelephone2() {
        return this.telephone2;
    }
    
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(Integer photo) {
        this.photo = photo;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }

@Override
public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MEmployee) ) return false;
		 MEmployee castOther = ( MEmployee ) other; 

	if(!java.util.Objects.equals(this.hash, castOther.hash)) {
            return false;
     }
	if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
     }
	if(!java.util.Objects.equals(this.branch, castOther.branch)) {
            return false;
     }
	if(!java.util.Objects.equals(this.nicNo, castOther.nicNo)) {
            return false;
     }
	if(!java.util.Objects.equals(this.salutation, castOther.salutation)) {
            return false;
     }
	if(!java.util.Objects.equals(this.name, castOther.name)) {
            return false;
     }
	if(!java.util.Objects.equals(this.fullName, castOther.fullName)) {
            return false;
     }
	if(!java.util.Objects.equals(this.addressLine1, castOther.addressLine1)) {
            return false;
     }
	if(!java.util.Objects.equals(this.addressLine2, castOther.addressLine2)) {
            return false;
     }
	if(!java.util.Objects.equals(this.addressLine3, castOther.addressLine3)) {
            return false;
     }
	if(!java.util.Objects.equals(this.mobile, castOther.mobile)) {
            return false;
     }
	if(!java.util.Objects.equals(this.telephone1, castOther.telephone1)) {
            return false;
     }
	if(!java.util.Objects.equals(this.telephone2, castOther.telephone2)) {
            return false;
     }
	if(!java.util.Objects.equals(this.fax, castOther.fax)) {
            return false;
     }
	if(!java.util.Objects.equals(this.email, castOther.email)) {
            return false;
     }
	if(!java.util.Objects.equals(this.note, castOther.note)) {
            return false;
     }
	if(!java.util.Objects.equals(this.active, castOther.active)) {
            return false;
     }
         
		 return true;
   }

   @Override
   public int hashCode() {
         int result = 17;
         
	result = result * 17 + java.util.Objects.hashCode(this.hash);
	result = result * 17 + java.util.Objects.hashCode(this.code);
	result = result * 17 + java.util.Objects.hashCode(this.branch);
	result = result * 17 + java.util.Objects.hashCode(this.nicNo);
	result = result * 17 + java.util.Objects.hashCode(this.salutation);
	result = result * 17 + java.util.Objects.hashCode(this.name);
	result = result * 17 + java.util.Objects.hashCode(this.fullName);
	result = result * 17 + java.util.Objects.hashCode(this.addressLine1);
	result = result * 17 + java.util.Objects.hashCode(this.addressLine2);
	result = result * 17 + java.util.Objects.hashCode(this.addressLine3);
	result = result * 17 + java.util.Objects.hashCode(this.mobile);
	result = result * 17 + java.util.Objects.hashCode(this.telephone1);
	result = result * 17 + java.util.Objects.hashCode(this.telephone2);
	result = result * 17 + java.util.Objects.hashCode(this.fax);
	result = result * 17 + java.util.Objects.hashCode(this.email);
	result = result * 17 + java.util.Objects.hashCode(this.note);
	result = result * 17 + java.util.Objects.hashCode(this.active);

         return result;
   }   

}


