package com.mac.zsystem.permission.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Jul 2, 2015 3:46:30 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * MReport generated by hbm2java
 */
public class MReport  implements java.io.Serializable {


     private String code;
     private String name;
     private String category;
     private byte[] report;
     private Set<RUserRole> RUserRoles = new HashSet<RUserRole>(0);

    public MReport() {
    }

	
    public MReport(String code, String name, String category, byte[] report) {
        this.code = code;
        this.name = name;
        this.category = category;
        this.report = report;
    }
    public MReport(String code, String name, String category, byte[] report, Set<RUserRole> RUserRoles) {
       this.code = code;
       this.name = name;
       this.category = category;
       this.report = report;
       this.RUserRoles = RUserRoles;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public byte[] getReport() {
        return this.report;
    }
    
    public void setReport(byte[] report) {
        this.report = report;
    }
    public Set<RUserRole> getRUserRoles() {
        return this.RUserRoles;
    }
    
    public void setRUserRoles(Set<RUserRole> RUserRoles) {
        this.RUserRoles = RUserRoles;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }

@Override
public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MReport) ) return false;
		 MReport castOther = ( MReport ) other; 

	if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
     }
	if(!java.util.Objects.equals(this.name, castOther.name)) {
            return false;
     }
	if(!java.util.Objects.equals(this.category, castOther.category)) {
            return false;
     }
	if(!java.util.Objects.equals(this.report, castOther.report)) {
            return false;
     }
         
		 return true;
   }

   @Override
   public int hashCode() {
         int result = 17;
         
	result = result * 17 + java.util.Objects.hashCode(this.code);
	result = result * 17 + java.util.Objects.hashCode(this.name);
	result = result * 17 + java.util.Objects.hashCode(this.category);
	result = result * 17 + java.util.Objects.hashCode(this.report);

         return result;
   }   

}


