package com.mac.zsystem.permission.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Jul 2, 2015 3:46:30 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * RPermission generated by hbm2java
 */
public class RPermission  implements java.io.Serializable {


     private String code;
     private String name;
     private String class_;
     private Set<RUserRole> RUserRoles = new HashSet<RUserRole>(0);

    public RPermission() {
    }

	
    public RPermission(String code, String name, String class_) {
        this.code = code;
        this.name = name;
        this.class_ = class_;
    }
    public RPermission(String code, String name, String class_, Set<RUserRole> RUserRoles) {
       this.code = code;
       this.name = name;
       this.class_ = class_;
       this.RUserRoles = RUserRoles;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public Set<RUserRole> getRUserRoles() {
        return this.RUserRoles;
    }
    
    public void setRUserRoles(Set<RUserRole> RUserRoles) {
        this.RUserRoles = RUserRoles;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }

@Override
public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RPermission) ) return false;
		 RPermission castOther = ( RPermission ) other; 

	if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
     }
	if(!java.util.Objects.equals(this.name, castOther.name)) {
            return false;
     }
	if(!java.util.Objects.equals(this.class_, castOther.class_)) {
            return false;
     }
         
		 return true;
   }

   @Override
   public int hashCode() {
         int result = 17;
         
	result = result * 17 + java.util.Objects.hashCode(this.code);
	result = result * 17 + java.util.Objects.hashCode(this.name);
	result = result * 17 + java.util.Objects.hashCode(this.class_);

         return result;
   }   

}


