package com.mac.registration.transactor.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Feb 11, 2015 3:03:05 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.HashSet;
import java.util.Set;

/**
 * MTransactorCategory generated by hbm2java
 */
public class MTransactorCategory  implements java.io.Serializable {


     private String hash;
     private String code;
     private String branch;
     private String name;
     private Set<MTransactor> MTransactors = new HashSet<MTransactor>(0);

    public MTransactorCategory() {
    }

	
    public MTransactorCategory(String hash, String code, String branch, String name) {
        this.hash = hash;
        this.code = code;
        this.branch = branch;
        this.name = name;
    }
    public MTransactorCategory(String hash, String code, String branch, String name, Set<MTransactor> MTransactors) {
       this.hash = hash;
       this.code = code;
       this.branch = branch;
       this.name = name;
       this.MTransactors = MTransactors;
    }
   
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<MTransactor> getMTransactors() {
        return this.MTransactors;
    }
    
    public void setMTransactors(Set<MTransactor> MTransactors) {
        this.MTransactors = MTransactors;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MTransactorCategory) ){
			return false;
		}
		
		MTransactorCategory castOther = ( MTransactorCategory ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


