package com.mac.transaction.transaction_registration.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On May 15, 2015 12:29:03 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MBranch generated by hbm2java
 */
public class MBranch  implements java.io.Serializable {


     private String code;
     private MCompany MCompany;
     private String name;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private String hotline;
     private String telephone1;
     private String telephone2;
     private String fax;
     private String email;
     private String note;
     private Date workingDate;
     private boolean active;
     private Set<MStore> MStores = new HashSet<MStore>(0);

    public MBranch() {
    }

	
    public MBranch(String code, String name, String addressLine1, String addressLine2, String addressLine3, String hotline, String telephone1, String telephone2, String fax, String email, String note, Date workingDate, boolean active) {
        this.code = code;
        this.name = name;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.addressLine3 = addressLine3;
        this.hotline = hotline;
        this.telephone1 = telephone1;
        this.telephone2 = telephone2;
        this.fax = fax;
        this.email = email;
        this.note = note;
        this.workingDate = workingDate;
        this.active = active;
    }
    public MBranch(String code, MCompany MCompany, String name, String addressLine1, String addressLine2, String addressLine3, String hotline, String telephone1, String telephone2, String fax, String email, String note, Date workingDate, boolean active, Set<MStore> MStores) {
       this.code = code;
       this.MCompany = MCompany;
       this.name = name;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.hotline = hotline;
       this.telephone1 = telephone1;
       this.telephone2 = telephone2;
       this.fax = fax;
       this.email = email;
       this.note = note;
       this.workingDate = workingDate;
       this.active = active;
       this.MStores = MStores;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public MCompany getMCompany() {
        return this.MCompany;
    }
    
    public void setMCompany(MCompany MCompany) {
        this.MCompany = MCompany;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }
    public String getHotline() {
        return this.hotline;
    }
    
    public void setHotline(String hotline) {
        this.hotline = hotline;
    }
    public String getTelephone1() {
        return this.telephone1;
    }
    
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }
    public String getTelephone2() {
        return this.telephone2;
    }
    
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getWorkingDate() {
        return this.workingDate;
    }
    
    public void setWorkingDate(Date workingDate) {
        this.workingDate = workingDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set<MStore> getMStores() {
        return this.MStores;
    }
    
    public void setMStores(Set<MStore> MStores) {
        this.MStores = MStores;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MBranch) ){
			return false;
		}
		
		MBranch castOther = ( MBranch ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


