package com.mac.reports.report_parameter.transaction_type_object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Mar 4, 2015 3:59:46 PM 
  *	Mohan Hibernate Mapping Generator
  */



/**
 * RTransactionType generated by hbm2java
 */
public class RTransactionType  implements java.io.Serializable {


     private String code;
     private String name;
     private String formType;
     private String type;
     private boolean itemIn;
     private boolean itemOut;
     private String inStore;
     private String outStore;
     private boolean fixedPrice;
     private String priceType;
     private boolean percentageDiscount;
     private boolean expireDate;
     private boolean client;
     private boolean supplier;
     private boolean active;

    public RTransactionType() {
    }

	
    public RTransactionType(String code, String name, String formType, String type, boolean itemIn, boolean itemOut, boolean fixedPrice, String priceType, boolean percentageDiscount, boolean expireDate, boolean client, boolean supplier, boolean active) {
        this.code = code;
        this.name = name;
        this.formType = formType;
        this.type = type;
        this.itemIn = itemIn;
        this.itemOut = itemOut;
        this.fixedPrice = fixedPrice;
        this.priceType = priceType;
        this.percentageDiscount = percentageDiscount;
        this.expireDate = expireDate;
        this.client = client;
        this.supplier = supplier;
        this.active = active;
    }
    public RTransactionType(String code, String name, String formType, String type, boolean itemIn, boolean itemOut, String inStore, String outStore, boolean fixedPrice, String priceType, boolean percentageDiscount, boolean expireDate, boolean client, boolean supplier, boolean active) {
       this.code = code;
       this.name = name;
       this.formType = formType;
       this.type = type;
       this.itemIn = itemIn;
       this.itemOut = itemOut;
       this.inStore = inStore;
       this.outStore = outStore;
       this.fixedPrice = fixedPrice;
       this.priceType = priceType;
       this.percentageDiscount = percentageDiscount;
       this.expireDate = expireDate;
       this.client = client;
       this.supplier = supplier;
       this.active = active;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFormType() {
        return this.formType;
    }
    
    public void setFormType(String formType) {
        this.formType = formType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isItemIn() {
        return this.itemIn;
    }
    
    public void setItemIn(boolean itemIn) {
        this.itemIn = itemIn;
    }
    public boolean isItemOut() {
        return this.itemOut;
    }
    
    public void setItemOut(boolean itemOut) {
        this.itemOut = itemOut;
    }
    public String getInStore() {
        return this.inStore;
    }
    
    public void setInStore(String inStore) {
        this.inStore = inStore;
    }
    public String getOutStore() {
        return this.outStore;
    }
    
    public void setOutStore(String outStore) {
        this.outStore = outStore;
    }
    public boolean isFixedPrice() {
        return this.fixedPrice;
    }
    
    public void setFixedPrice(boolean fixedPrice) {
        this.fixedPrice = fixedPrice;
    }
    public String getPriceType() {
        return this.priceType;
    }
    
    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }
    public boolean isPercentageDiscount() {
        return this.percentageDiscount;
    }
    
    public void setPercentageDiscount(boolean percentageDiscount) {
        this.percentageDiscount = percentageDiscount;
    }
    public boolean isExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(boolean expireDate) {
        this.expireDate = expireDate;
    }
    public boolean isClient() {
        return this.client;
    }
    
    public void setClient(boolean client) {
        this.client = client;
    }
    public boolean isSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(boolean supplier) {
        this.supplier = supplier;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof RTransactionType) ){
			return false;
		}
		
		RTransactionType castOther = ( RTransactionType ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


