package com.mac.zsystem.item_utils.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Jan 13, 2015 3:25:13 PM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.Date;

/**
 * MItemBatch generated by hbm2java
 */
public class MItemBatch  implements java.io.Serializable {


     private Integer indexNo;
     private MItem MItem;
     private String batchCode;
     private double salePrice;
     private double lastSalesPrice;
     private double wholeSalePrice;
     private double costPrice;
     private double averagePrice;
     private Date dateTime;

    public MItemBatch() {
    }

    public MItemBatch(MItem MItem, String batchCode, double salePrice, double lastSalesPrice, double wholeSalePrice, double costPrice, double averagePrice, Date dateTime) {
       this.MItem = MItem;
       this.batchCode = batchCode;
       this.salePrice = salePrice;
       this.lastSalesPrice = lastSalesPrice;
       this.wholeSalePrice = wholeSalePrice;
       this.costPrice = costPrice;
       this.averagePrice = averagePrice;
       this.dateTime = dateTime;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public MItem getMItem() {
        return this.MItem;
    }
    
    public void setMItem(MItem MItem) {
        this.MItem = MItem;
    }
    public String getBatchCode() {
        return this.batchCode;
    }
    
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode;
    }
    public double getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(double salePrice) {
        this.salePrice = salePrice;
    }
    public double getLastSalesPrice() {
        return this.lastSalesPrice;
    }
    
    public void setLastSalesPrice(double lastSalesPrice) {
        this.lastSalesPrice = lastSalesPrice;
    }
    public double getWholeSalePrice() {
        return this.wholeSalePrice;
    }
    
    public void setWholeSalePrice(double wholeSalePrice) {
        this.wholeSalePrice = wholeSalePrice;
    }
    public double getCostPrice() {
        return this.costPrice;
    }
    
    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }
    public double getAveragePrice() {
        return this.averagePrice;
    }
    
    public void setAveragePrice(double averagePrice) {
        this.averagePrice = averagePrice;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }





	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof MItemBatch) ){
			return false;
		}
		
		MItemBatch castOther = ( MItemBatch ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


