package com.mac.zsystem.payment.hibernate;

/**
  *	@author Channa Mohan
  *	
  *	Created On Jun 9, 2015 11:33:12 AM 
  *	Mohan Hibernate Mapping Generator
  */


import java.util.Date;

/**
 * TCheque generated by hbm2java
 */
public class TCheque  implements java.io.Serializable {


     private Integer indexNo;
     private MBankBranch MBankBranch;
     private String branch;
     private String client;
     private int transactionSummary;
     private String accountNo;
     private String chequeNo;
     private double amount;
     private Date chequeDate;
     private String depositDate;
     private Date realizeDate;
     private Date returnDate;
     private String status;

    public TCheque() {
    }

	
    public TCheque(MBankBranch MBankBranch, String branch, String client, int transactionSummary, String accountNo, String chequeNo, double amount, String status) {
        this.MBankBranch = MBankBranch;
        this.branch = branch;
        this.client = client;
        this.transactionSummary = transactionSummary;
        this.accountNo = accountNo;
        this.chequeNo = chequeNo;
        this.amount = amount;
        this.status = status;
    }
    public TCheque(MBankBranch MBankBranch, String branch, String client, int transactionSummary, String accountNo, String chequeNo, double amount, Date chequeDate, String depositDate, Date realizeDate, Date returnDate, String status) {
       this.MBankBranch = MBankBranch;
       this.branch = branch;
       this.client = client;
       this.transactionSummary = transactionSummary;
       this.accountNo = accountNo;
       this.chequeNo = chequeNo;
       this.amount = amount;
       this.chequeDate = chequeDate;
       this.depositDate = depositDate;
       this.realizeDate = realizeDate;
       this.returnDate = returnDate;
       this.status = status;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public MBankBranch getMBankBranch() {
        return this.MBankBranch;
    }
    
    public void setMBankBranch(MBankBranch MBankBranch) {
        this.MBankBranch = MBankBranch;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public int getTransactionSummary() {
        return this.transactionSummary;
    }
    
    public void setTransactionSummary(int transactionSummary) {
        this.transactionSummary = transactionSummary;
    }
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getChequeNo() {
        return this.chequeNo;
    }
    
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Date getChequeDate() {
        return this.chequeDate;
    }
    
    public void setChequeDate(Date chequeDate) {
        this.chequeDate = chequeDate;
    }
    public String getDepositDate() {
        return this.depositDate;
    }
    
    public void setDepositDate(String depositDate) {
        this.depositDate = depositDate;
    }
    public Date getRealizeDate() {
        return this.realizeDate;
    }
    
    public void setRealizeDate(Date realizeDate) {
        this.realizeDate = realizeDate;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }





	@Override
	public boolean equals(Object other) {
		if (this == other){
			return true;
		}
			 
		if (other == null){
			return false;
		}
		
		if ( !(other instanceof TCheque) ){
			return false;
		}
		
		TCheque castOther = ( TCheque ) other; 

		if(this.indexNo==null && castOther.indexNo==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.indexNo, castOther.indexNo)) {
			return false;
		}
			 
		return true;
	}

    @Override
    public int hashCode() {
        int result = 17;
        
		result = result * 17 + java.util.Objects.hashCode(this.indexNo);

        return result;
    }





}


