package com.mac.registration.company.object;

/**
  *	@author Channa Mohan
  *	
  *	Created On Feb 28, 2015 5:23:22 PM 
  *	Mohan Hibernate Mapping Generator
  */



/**
 * MCompany generated by hbm2java
 */
public class MCompany  implements java.io.Serializable {


     private String code;
     private String name;

    public MCompany() {
    }

    public MCompany(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


	@Override
     public String toString() {
		return code + "-" + name;
     }




	@Override
	public boolean equals(Object other) {
        if ( (this == other ) ){
			return true;
		}
		
		if ( (other == null ) ){
			return false;
		}
		
		if ( !(other instanceof MCompany) ){
			return false;
		}
		
		MCompany castOther = ( MCompany ) other; 

		if(this.code==null && castOther.code==null) {
			return false;
		}
		
		if(!java.util.Objects.equals(this.code, castOther.code)) {
            return false;
		}
        
		return true;
   }

    @Override
    public int hashCode() {
        int result = 17;
         
		result = result * 17 + java.util.Objects.hashCode(this.code);

        return result;
    }




}


