package com.mac.registration.bank.object;
// Generated Dec 23, 2014 12:00:43 PM by Hibernate Tools 3.2.1.GA



/**
 * MBank generated by hbm2java
 */
public class MBank  implements java.io.Serializable {


     private String code;
     private String name;

    public MBank() {
    }

	
    public MBank(String code) {
        this.code = code;
    }
    public MBank(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


