package com.mac.registration.bank_branch.object;
// Generated Dec 23, 2014 12:01:29 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MBank generated by hbm2java
 */
public class MBank implements java.io.Serializable {

    private String code;
    private String name;
    private Set<MBankBranch> MBankBranchs = new HashSet<MBankBranch>(0);

    public MBank() {
    }

    public MBank(String code) {
        this.code = code;
    }

    public MBank(String code, String name, Set<MBankBranch> MBankBranchs) {
        this.code = code;
        this.name = name;
        this.MBankBranchs = MBankBranchs;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<MBankBranch> getMBankBranchs() {
        return this.MBankBranchs;
    }

    public void setMBankBranchs(Set<MBankBranch> MBankBranchs) {
        this.MBankBranchs = MBankBranchs;
    }

    @Override
    public String toString() {
        return code + "-" + name;
    }
}
