package com.mac.registration.bank_branch.object;
// Generated Dec 23, 2014 12:01:29 PM by Hibernate Tools 3.2.1.GA



/**
 * MBankBranch generated by hbm2java
 */
public class MBankBranch  implements java.io.Serializable {


     private String code;
     private MBank MBank;
     private String name;

    public MBankBranch() {
    }

	
    public MBankBranch(String code) {
        this.code = code;
    }
    public MBankBranch(String code, MBank MBank, String name) {
       this.code = code;
       this.MBank = MBank;
       this.name = name;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public MBank getMBank() {
        return this.MBank;
    }
    
    public void setMBank(MBank MBank) {
        this.MBank = MBank;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


